development:
  clients:
    default:
      uri: "mongodb+srv://amc92v:123456@cluster0.yjptpuq.mongodb.net/blog_development?retryWrites=true&w=majority&appName=Cluster0"



test:
  clients:
    default:
      database: blog_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      