development:
  clients:
    default:
      uri: <%= ENV['MONGODB_DEV_URI'] %>

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_TEST_URI'] %>

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>